# Generated by Django 6.0.3 on 2026-05-10 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0003_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="certificate_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="lms_app.course",
            ),
        ),
    ]
