# Generated by Django 6.0.3 on 2026-05-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lms_app",
            "0004_course_video_courseenrollment_certificate_generated_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoprogress",
            old_name="watched",
            new_name="completed",
        ),
        migrations.AlterUniqueTogether(
            name="videoprogress",
            unique_together={("student", "video")},
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lms_app.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lms_app.user"
                    ),
                ),
            ],
        ),
    ]
