# Generated by Django 6.0.3 on 2026-05-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0005_rename_watched_videoprogress_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
