# Generated by Django 6.0.3 on 2026-05-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0006_courseenrollment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video",
        ),
    ]
